# frozen_string_literal: true

source 'https://rubygems.org'

gem 'capybara', '3.36.0'
gem 'cpf_faker'
gem 'cucumber', '3.1.2'
gem 'dotenv'
gem 'faker'
gem 'faker_credit_card'
gem 'ffi'
gem 'httparty', '0.18.1'
gem 'nokogiri', '1.11.0'
gem 'overcommit'
gem 'pdf-reader'
gem 'pry'
gem 'report_builder'
gem 'rspec', '3.9.0'
gem 'rspec-retry', '0.6.2'
gem 'rubocop', '1.7.0', require: false
gem 'selenium-webdriver'
gem 'site_prism', '3.4.2'
